Portfolio/projects/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField,TextAreaField

class ProjectForm(FlaskForm):
    projects = StringField("Projects")
    project_title = StringField("Title")
    project_overview =TextAreaField("Overview",render_kw={'row':3})
    project_url =StringField("Link")
    add = SubmitField("Add")
    done = SubmitField("Done")
    # remove = SubmitField('Remove')

Portfolio/qualifications/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField

class QualificationsForm(FlaskForm):
    update = SubmitField("Update")
    course = StringField('Course')

Portfolio/skills/forms.py
from flask_wtf import FlaskForm 
from wtforms import StringField, SubmitField,IntegerField
from wtforms.validators import NumberRange


class SkillForm(FlaskForm):
    update = SubmitField("Update")

def create_skill_form():
    class DynamicSkillForm(SkillForm):
        pass

    for i in range(1, 8):
        setattr(DynamicSkillForm, f'skill_{i}', StringField(f"Skill {i}"))
        setattr(DynamicSkillForm, f'skill_value_{i}', IntegerField(f"Skill {i} Range",validators=[NumberRange(min=0,max=100)]))

    return DynamicSkillForm()

Portfolio/main/routes.py
from Portfolio import db
import flask
from flask import Blueprint 
from Portfolio.main.forms import EditProfile,searchForm
from flask import render_template, url_for,flash,redirect,request
from Portfolio.models import User,Project,Skills,Qualifications
from flask_login import login_user,current_user,logout_user,login_required
from Portfolio.main.utils import save_picture,save_resume

main = Blueprint('main',__name__)

@main.route("/home",methods=['GET','POST'])
def home():
    form = searchForm()
    page = request.args.get('page',1,type=int)
    users = User.query.paginate(per_page=3,page=page)
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.input.data.strip()).first()
        if user:
            return redirect(url_for('main.home_search',username=form.input.data.strip()))
        else:
            return redirect(url_for('main.user_not_found'))
    return render_template("home.html",users=users,form=form )

@main.route("/home/<username>",methods=['GET','POST'])
def home_search(username):
    user = User.query.filter_by(username=username).first()
    return render_template("home_search.html",user=user)

@main.route("/home/user_not_found")
def user_not_found():
    return render_template('user_not_found.html')

@main.route("/user/<username>")
def user_profile(username):
    # page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    projects = Project.query.filter_by(user_id = user.id)
    skills = Skills.query.filter_by(user_id = user.id)
    qualifications = Qualifications.query.filter_by(user_id = user.id)
    return render_template("user_profile.html",user=user)

# @main.route("/yourprofile",methods=['GET','POST'])
# @login_required
# def yourprofile():
#     image_file = url_for('static',filename='/profile_pics/'+current_user.image_file)
#     return render_template('yourprofile.html',title='Your Profile',image_file=image_file)



@main.route("/editprofile",methods=['GET','POST'])
@login_required
def editprofile():
    form = EditProfile()
    image_file = url_for('static',filename='profile_pics/' + current_user.image_file)
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        if form.dob.data:
            if form.dob.data != current_user.DOB:
                current_user.DOB = form.dob.data
        if form.resume.data :
            resume_file = save_resume(form.resume.data)
            current_user.resume = resume_file
        if form.profile_overview.data :
            if form.profile_overview.data != current_user.profile_overview:
                current_user.profile_overview =form.profile_overview.data
        if form.experience.data :
            current_user.experience = form.experience.data 
        current_user.email = form.email.data 
        current_user.username = form.username.data 
        db.session.commit()
        flash("Your Profile has been updated!!",'success')
        return redirect(url_for('main.editprofile'))
    elif request.method == 'GET':
        form.username.data = current_user.username 
        form.email.data = current_user.email 
        form.dob.data = current_user.DOB
        form.profile_overview.data = current_user.profile_overview
        form.experience.data = current_user.experience
    return render_template('editprofile.html',image_file=image_file,title='Edit profile',form = form)


@main.route("/sign_out")
def sign_out():
    logout_user()
    return redirect(url_for('main.home'))

Portfolio/projects/routes.py
from Portfolio import db
import flask 
from Portfolio.projects.forms import ProjectForm
from flask import render_template, url_for,flash,redirect,request
from Portfolio.models import Project
from flask_login import login_user,current_user,login_required
from flask import Blueprint 

projects_blueprint = Blueprint('projects_blueprint',__name__)

@projects_blueprint.route("/projects",methods=['GET'])
@login_required
def projects():
    projects = Project.query.filter_by(user_id=current_user.id).all()
    return render_template('projects.html',projects=projects)

@projects_blueprint.route("/projects/<int:project_id>",methods=['GET','POST'])
@login_required
def curr_project(project_id):
    # projects = Project.query.filter_by(user_id=current_user.id).all()
    curr_project = Project.query.get_or_404(project_id)
    return render_template('curr_projects.html',curr_project=curr_project)


@projects_blueprint.route("/projects/<int:project_id>/update",methods=['GET','POST'])
@login_required
def update_project(project_id):
    form = ProjectForm()
    curr_project = Project.query.get_or_404(project_id)
    if form.validate_on_submit():
        curr_project.project_title = form.project_title.data
        curr_project.project_overview = form.project_overview.data
        curr_project.project_url = form.project_url.data
        db.session.commit()
        flash(f"Your project {curr_project.project_title} has been updated",'success')
        return redirect(url_for('projects_blueprint.projects'))
    elif request.method == "GET":
        form.project_title.data = curr_project.project_title    
        form.project_overview.data = curr_project.project_overview
        form.project_url.data = curr_project.project_url
    return render_template('add_project.html',curr_project=curr_project,form=form)

@projects_blueprint.route("/projects/<int:project_id>/delete",methods=['POST'])
@login_required
def delete_project(project_id):
    curr_project = Project.query.get_or_404(project_id)
    db.session.delete(curr_project)
    db.session.commit()
    flash("Your project has been deleted",'success')
    return redirect(url_for('projects_blueprint.projects'))

@projects_blueprint.route("/projects/add_projects",methods=['GET','POST'])
@login_required
def add_project():
    form = ProjectForm()
    if form.validate_on_submit():
        project = Project(project_title=form.project_title.data, project_overview=form.project_overview.data,
                           project_url=form.project_url.data,user_id=current_user.id)
        db.session.add(project)
        db.session.commit()
        flash('Your Project has been added !!','success')
        return redirect(url_for('projects_blueprint.projects'))
    return render_template('add_project.html',form=form)

Portfolio/qualifications/routes.py
from Portfolio import db
import flask 
from Portfolio.qualifications.forms import QualificationsForm
from flask import render_template, url_for,flash,redirect,request
from Portfolio.models import Qualifications
from flask_login import current_user,login_required
from flask import Blueprint 

qualifications_blueprint = Blueprint('qualifications_blueprint',__name__)

@qualifications_blueprint.route("/qualifications", methods=['GET', 'POST'])
@login_required
def qualifications():
    user_qualifications = Qualifications.query.filter_by(user_id=current_user.id).all()
    return render_template('qualifications.html', user_qualifications=user_qualifications)

@qualifications_blueprint.route("/qualifications/add_qualification", methods=['GET', 'POST'])
@login_required
def add_qualification():
    form = QualificationsForm()
    if form.validate_on_submit():
        Course = Qualifications(course=form.course.data,user_id = current_user.id)
        db.session.add(Course)
        db.session.commit()
        flash("Your Quallification has been added!!",'success')
        return redirect(url_for('qualifications_blueprint.qualifications'))
   
    return render_template('add_qualification.html', form=form)


@qualifications_blueprint.route("/qualifications/<int:qualification_id>",methods=['GET','POST'])
@login_required
def curr_qualification(qualification_id):
    curr_qualification = Qualifications.query.get_or_404(qualification_id)
    return render_template('curr_qualification.html',curr_qualification=curr_qualification)

@qualifications_blueprint.route("/qualifications/<int:qualification_id>/update",methods=['GET','POST'])
@login_required
def update_qualification(qualification_id):
    form = QualificationsForm()
    curr_qualification = Qualifications.query.get_or_404(qualification_id)
    if form.validate_on_submit():
        print(f"Form data before update: {form.course.data}")
        print(f"Current qualification course before update: {curr_qualification.course}")
        curr_qualification.course = form.course.data

        db.session.commit()
        flash(f"Your qualifications {curr_qualification.course} has been updated",'success')
        return redirect(url_for('qualifications_blueprint.qualifications'))
    elif request.method == "GET":
        form.course.data = curr_qualification.course
    return render_template('add_qualification.html',curr_qualification=curr_qualification,form=form)

@qualifications_blueprint.route("/qualifications/<int:qualification_id>/delete",methods=['POST'])
@login_required
def delete_qualification(qualification_id):
    curr_qualification = Qualifications.query.get_or_404(qualification_id)
    db.session.delete(curr_qualification)
    db.session.commit()
    flash("Your qualifications has been deleted",'success')
    return redirect(url_for('qualifications_blueprint.qualifications'))

Portfolio/skills/routes.py
from Portfolio import db 
import flask 
from Portfolio.skills.forms import create_skill_form
from flask import render_template, url_for,flash,redirect,request
from Portfolio.models import Skills
from flask_login import current_user,login_required
from flask import Blueprint 

skills_blueprint = Blueprint('skills_blueprint',__name__)


@skills_blueprint.route("/skills/add_skill",methods=['GET','POST'])
@login_required
def add_skill():
    form = create_skill_form()
    skills =[request.form.get(f"skill_{i}") for i in range(1,8)]
    skill_values =[request.form.get(f"skill_value_{i}") for i in range(1,8)]

    if form.validate_on_submit():
    # Fetch existing skills data from the database for the current user
        existing_skills = Skills.query.filter_by(user_id=current_user.id).all()

        # Update the existing skills or create new ones if needed
        for i, (skill_name, skill_value) in enumerate(zip(skills, skill_values), start=1):
            if i <= 7:
                # Check if a skill with the same name already exists
                existing_skill = next((s for s in existing_skills if s.skill_name == skill_name), None)

                if existing_skill:
                    # Update the existing skill
                    existing_skill.skill_value = skill_value
                else:
                    # Create a new skill
                    new_skill = Skills(skill_name=skill_name, skill_value=skill_value, user_id=current_user.id)
                    db.session.add(new_skill)

        db.session.commit()
        flash('Your skills have been updated', 'info')
        return redirect(url_for('skills_blueprint.skills'))

    if request.method == 'GET':
        existing_skills = Skills.query.filter_by(user_id=current_user.id).all()

        for i, skill in enumerate(existing_skills, start=1):
            if i <= 7:
                form[f'skill_{i}'].data = skill.skill_name
                form[f'skill_value_{i}'].data = skill.skill_value


    return render_template('add_skill.html',form = form)

@skills_blueprint.route("/skills",methods=['GET','POST'])
@login_required
def skills():
    user_skills = Skills.query.filter_by(user_id=current_user.id).all() 
    return render_template('skills.html',user_skills=user_skills)

Portfolio/users/routes.py
from flask import Blueprint
from Portfolio import db,bcrypt 
import flask 
from Portfolio.users.forms import LoginForm,RegistrationForm 
from flask import render_template, url_for,flash,redirect,request
from Portfolio.models import User,Project,Skills,Qualifications
from flask_login import login_user,current_user,login_required
from Portfolio.users.utils import is_safe_url

users_blueprint = Blueprint('users_blueprint',__name__)

@users_blueprint.route("/",methods=['GET','POST'])
def sign_in():
    if current_user.is_authenticated:
        flash(f"logged in as {current_user.username}")
        return redirect(url_for("main.home"))
    form  = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            flash(f"Login successful for {form.email.data}",'success')
            next = request.args.get('next')
            if next and not is_safe_url(next):
                return flask.abort(400)
            return redirect(next or url_for('main.home')) 
        else:
            flash("Wrong email or password,please try again",'error')
    return render_template("signin.html",title = "Login",form = form)




@users_blueprint.route("/signup",methods=['GET','POST'])
def sign_up():  
    if current_user.is_authenticated:
        flash(f"logged in as{current_user.username}")
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        #Hash Password and store all information in the database 
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username = form.username.data.strip(),email = form.email.data.strip(),password = hashed_password)
        # users_blueprint.app_context().push()
        db.session.add(user)
        db.session.commit()
        flash(f"Account created for {form.username.data}",'success')
        return redirect(url_for('main.home'))
    if request.method == "POST":
        # for field,error in form.errors.items():
        #     flash(error [0], f'danger_{field}')
        # else:
        #     flash("Account not created. Please check your inputs.", 'danger')
        return render_template("sign_up.html",title ="Sign Up",form = form)

    return render_template("sign_up.html",title ="Sign Up",form = form)

@users_blueprint.route('/show_signup')
def show_sign_up():
    return render_template("sign_up.html", title="Sign Up", form=RegistrationForm())

def delete_user(user_id):
    # Get the user by ID
    user = User.query.get(user_id)

    if user:
        try:
            # Delete associated data (profile, project, skills, qualifications)
            print(f"Deleting associated data for user {user_id}")
            Project.query.filter_by(user_id=user.id).delete()
            Skills.query.filter_by(user_id=user.id).delete()
            Qualifications.query.filter_by(user_id=user.id).delete()

            # Delete the user
            print(f"Deleting user {user_id}")   
            db.session.delete(user)
            db.session.commit()

            print(f"User {user_id} deleted successfully")
            return True
        except Exception as e:
            # Handle exceptions (e.g., database errors)
            print(f"Error deleting user {user_id}: {e}")
            db.session.rollback()
            return False
    else:
        print(f"User {user_id} not found")
        return False
    
@users_blueprint.route("/editprofile/<int:user_id>/delete",methods = ["GET","POST"])
@login_required
def delete_account(user_id):
    # user_id = current_user.id
    delete_user(user_id)
    return redirect(url_for('users_blueprint.sign_up'))

Portfolio/templates/add_qualification.html
{% extends 'layouts_profile.html' %}
{% block content %}
<div class="jumbotron">
<form method="POST" action="{{ url_for('qualifications_blueprint.add_qualification') }}">
  <div class = 'form-group'>
    {{ form.hidden_tag() }}
    {{ form.course.label(class='form-control-label') }}
    {% if form.course.errors %} 
      {{ form.course(class='form-control is-invalid',placeholder="Course name and grades if applicable ") }}
      <div class="invalid-feedback" id="flash-messages">
        {% for error in form.course.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      </div>
    {% else %}
      {{ form.course(class='form-control form-floating',placeholder="Course name and grades if applicable ") }}
    {% endif %}
  </div>
  <div class="form-group " >  
    {{ form.update(class="btn btn-secondary mt-2") }}
  </div>
</form>
</div>
{% endblock %}

Portfolio/templates/curr_qualification.html
{% extends 'layouts_profile.html' %}
{% block content %}
<div class="jumbotron">
 <div class="form-control"> {{ curr_qualification.course }}</div>
  <div class="btn btn-group">
        <!-- Update button -->
        <a href='{{ url_for("qualifications_blueprint.update_qualification", qualification_id = curr_qualification.id) }}' class="btn btn-info">
          Update
        </a>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger ml-2" data-toggle="modal" data-target="#deleteModal">
          Delete 
        </button>
  </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Once deleted the project cannot be recovered</p>
          </div>
          <div class="modal-footer">  
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('qualifications_blueprint.delete_qualification', qualification_id = curr_qualification.id) }}" method="POST">
              <input type="submit" class="btn btn-danger" value ='Delete'>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

Portfolio/templates/home_search.html
{% extends 'layouts_profile.html' %}
{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Profiles</h1>
  <!-- <p class="lead">Add up to seven skills most relevant to you</p> -->
  <hr class="my-4">
  <div class="post-section">
    <article class="media content-section mt-3">

        <img src="{{ url_for('static',filename='profile_pics/' + (user.image_file or 'default.png')) }}" alt="Profile Picture Post" class="mr-3 img-fluid rounded-circle home-profile-image" width="50">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('main.user_profile',username=user.username)}}">{{ user.username }}</a>
                <small class="text-muted">{{ user.experience }}</small>
            </div>
            <p class="article-title" href="#">{{ user.profile_overview }}</p>
            <!-- Add more post details as needed -->
        </div>
    </article>
  </div>    
</div>

{% endblock content %}




John Doe
John Doe 

Portfolio/templates/layouts.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">
    <title>Top navbar example for Bootstrap</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link rel="stylesheet" href="{{url_for('static',filename='navbar-top.css')}}"> -->
    <link rel="stylesheet" type ="text/css" href="{{url_for('static',filename='main.css')}}">

  </head>

  <body>
    

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto ml-auto ">
          <li class="nav-item active ">
            <a class="nav-link" href="{{url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if current_user.is_authenticated %}
          
            <li class="nav-item active ml-md-1">
              <a class="nav-link" href="{{url_for('main.user_profile',username=current_user.username )}}">My Profile <span class="sr-only">(current)</span></a>
            </li>
              <div class="dropdown show">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Manage Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{{url_for('projects_blueprint.projects')}}">Projects</a>
                  <a class="dropdown-item" href="{{url_for('qualifications_blueprint.qualifications')}}">Qualifications</a>
                  <a class="dropdown-item" href="{{url_for('skills_blueprint.skills')}}">Skills</a>
                  <a class="dropdown-item" href="{{url_for('main.editprofile')}}">Edit Profile</a>

                </div>
              </div>
           
          {% endif %}
        
        </ul>     
        <form method = "POST" class="form-inline mt-1 mt-md-1 col-lg-3">
          {{ form.hidden_tag() }}
          {{ form.input(class = "form-control mr-sm-2",type="text", placeholder="Search" )}}
          {{ form.search(class="btn btn-outline-success my-2 my-sm-0 ")}}
        </form>
        <div class="navbar-nav col-lg-3">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link " href="{{url_for('main.sign_out')}}">Sign out</a>
          {% else %}
            <a class="nav-item nav-link mr-md-2" href="{{url_for('users_blueprint.sign_in')}}">Sign in</a>
            <a class="nav-item nav-link mr-md-2" href="{{url_for('users_blueprint.sign_up')}}">Sign up</a>
          {% endif %}
        </div> 
      </div>
    </nav>
    <div class="container">
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-11">
            <div class="flash-messages">
              {% with messages = get_flashed_messages(with_categories=True) %}
              {% if messages %}
                {% for category,message in messages %}
                <div class = 'alert alert-{{category}}'>
                  {{message}}
                </div>
                {% endfor %}
              {% endif %}
              {% endwith %}
            </div>
            {% block content %}{% endblock %}
          </div>
          <!-- <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div> -->
          </div>
        </div>
      </main>
    </div>
    <script>
      // Wait for the DOM to be ready
      document.addEventListener('DOMContentLoaded', function () {
          // Find the flash messages container
          var flashMessagesContainer = document.getElementById('flash-messages');
  
          // Hide flash messages after 5 seconds (5000 milliseconds)
          if (flashMessagesContainer) {
              setTimeout(function () {
                  flashMessagesContainer.innerHTML = '';  // Clear the content
              }, 5000);
          }
      });
    </script>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        
    
        
  
 <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

<!-- Bootstrap JS -->
<script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>

</body>
</html>

Portfolio/templates/layouts_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">
    <title>Top navbar example for Bootstrap</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link rel="stylesheet" href="{{url_for('static',filename='navbar-top.css')}}"> -->
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='main.css')}}">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto ml-auto ">
          <li class="nav-item active ">
            <a class="nav-link" href="{{url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if current_user.is_authenticated %}
          
            <li class="nav-item active ml-md-1">
              <a class="nav-link" href="{{url_for('main.user_profile',username=current_user.username )}}">My Profile <span class="sr-only">(current)</span></a>
            </li>
              <div class="dropdown show">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Manage Profile
                </a>
                
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{{url_for('projects_blueprint.projects')}}">Projects</a>
                  <a class="dropdown-item" href="{{url_for('qualifications_blueprint.qualifications')}}">Qualifications</a>
                  <a class="dropdown-item" href="{{url_for('skills_blueprint.skills')}}">Skills</a>
                  <a class="dropdown-item" href="{{url_for('main.editprofile')}}">Edit Profile</a>

                </div>
              </div>
          
          {% endif %}
         
        </ul>     
        <div class="navbar-nav col-lg-3">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link " href="{{url_for('main.sign_out')}}">Sign out</a>
          {% else %}
            <a class="nav-item nav-link mr-md-2" href="{{url_for('users_blueprint.sign_in')}}">Sign in</a>
            <a class="nav-item nav-link mr-md-2" href="{{url_for('users_blueprint.sign_up')}}">Sign up</a>
          {% endif %}
        </div> 
      </div>
    </nav>
    <div class="container">
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-11">
                    <div class="flash-messages">
                        {% with messages = get_flashed_messages(with_categories=True) %}
                            {% if messages %}
                                {% for category,message in messages %}
                                    <div class='alert alert-{{category}}'>
                                        {{message}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    </div>
                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>
    </div>
  
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

<!-- Bootstrap JS -->
<script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>


</body>
</html>

Portfolio/templates/projects.html
{% extends 'layouts_profile.html' %}
{% block content %}
<div class="jumbotron">
  <h1 class="display-4">My Projects</h1>
  <p class="lead">Projects help display what you the best, make sure you display all your best ones</p>
  <hr class="my-4">
  {% for project in projects %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <div class="article-metadata article-metadata-head">
          <a  class="project-title-link" href="{{ url_for('projects_blueprint.curr_project',project_id = project.id) }}">{{ project.project_title }}</a>
        </div>
        <hr>
        <p class="text-muted">{{ project.project_overview }}</p>

  </article>
  {% endfor %}
  <a href='{{ url_for("projects_blueprint.add_project") }}'> 
      <button class="btn btn-info mb-2"> 
          Add new Project 
      </button> 
  </a> 

</div>

{% endblock content %}